### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by remysucre** [ryzhyk/differential-datalog#94] opened 2018-09-18 16:38 UTC
Should we set up travis CI?

**Comment by ryzhyk** [comment] 2018-09-18 16:46
That would of course be fantastic. There are two problems I am aware of. First, I don't think Travis supports stack-based Haskell projects out of the box. Second, I think Travis test runs are limited to 20 or 30 minutes, and unfortunately DDlog tests run longer.

Both issues can be solved.  There exist examples of setting up Travis for stack-based projects, and we can definitely construct a light version of the test suite that finishes in under 20 minutes.

If this is something you are willing to work on, it would be incredibly useful. And I can definitely help with speeding up tests.

**Comment by remysucre** [comment] 2018-09-18 16:54
I'm happy to give it a try!

**Comment by ryzhyk** [comment] 2018-09-18 16:58
Wonderful, thank you! Do you want to try it in your fork of the project or shall I add you as collaborator to differential-datalog?

**Comment by remysucre** [comment] 2018-09-18 17:02
What would be the difference?

**Comment by remysucre** [comment] 2018-09-18 17:09
Actually I should try it on my fork first, since the setup might be quite involving. Once I get it working I can replicate the setup here.

**Comment by ryzhyk** [comment] 2018-09-18 17:14
Ok, sounds good. Let me know how I can help. For the moment a "light" test suite could be just running one of the tests:

```
stack test --ta '-p tutorial'
```

**Comment by remysucre** [comment] 2018-09-18 22:18
Is there a good subset of tests to run? E.g. all parser tests & some compiler tests & ovsdb tests. Otherwise I can pick a few arbitrary compiler tests.

**Comment by ryzhyk** [comment] 2018-09-18 22:21
`tutorial`, `path`, `ovn`, and `ovn_ftl` is a reasonable subset.

**Comment by remysucre** [comment] 2018-09-19 04:17
The MacOS test passed on Travis, but for linux I'm getting `tutorial_test failed with exit code ExitFailure 2`. Could you check if the test `stack test --ta '-p tutorial' ` runs on linux?

**Comment by ryzhyk** [comment] 2018-09-19 05:00
Have you merged the latest master? Your macos fix broke the test script on Linux.

**Comment by remysucre** [comment] 2018-09-19 05:13
I did merge it, and tried to revert to the commit before my fix which didn't work either. Probably something wrong with the travis end. Any idea what `ExitFailure 2` might mean?

**Comment by ryzhyk** [comment] 2018-09-19 05:38
Hmm, I've seen it before.  I think it's "file not found" returned by one of the commands invoked from the test script. Do you have the full output? Is cargo installed in the test container?

If the error happens after the Rust project was created, you can try running cargo directly and observing its output:

```
cd test/datalog_tests/tutorial
cargo build --release
target/release/tutorial_cli  < ../tutorial.dat
```

**Comment by ryzhyk** [comment] 2018-09-19 05:47
Oh wait, the error mentions `tutorial_test`. Then can you please try:

```
LD_LIBRARY_PATH=test/datalog_tests/tutorial/target/release/  test/datalog_tests/tutorial/tutorial_test
```

but using absolute paths instead of relative.

**Comment by ryzhyk** [comment] 2018-09-19 06:13
I am checking out for today. I was not able to reproduce the bug so far. One way to proceed might be to migrate your travis setup to the main DDlog repo so I can take it from there. Whatever is happening on Linux, tests should not fail without a meaningful error message, so I should at least make sure that one is generated.

**Comment by remysucre** [comment] 2018-09-19 16:28
Thanks, made a PR that has the .travis files

**Comment by remysucre** [comment] 2018-09-19 23:45
I just ran the tutorial test on a fresh ubuntu vm and it passed, so must be something wrong with travis setup.

**Comment by ryzhyk** [comment] 2018-09-19 23:54
There used to be a nasty issue in that particular part of the test script related to lazy evaluation that could potentially manifest in a non-deterministic way. It's possible that I did not fix it properly. Still working on something else, but will get to this shortly...

**Comment by remysucre** [comment] 2018-09-20 00:08
Ah that might be it, I'll poke around a bit. Laziness usually messes up sys calls

**Comment by remysucre** [comment] 2018-09-20 00:46
one more detail before I head out - I ran `LD_LIBRARY_PATH=test/datalog_tests/tutorial/target/release/  test/datalog_tests/tutorial/tutorial_test` with the absolute path after `stack test` on travis; it had the same output as what I get locally, but still returned an `exit code 2` which is surprising

**Comment by ryzhyk** [comment] 2018-09-20 01:51
I am keeping the issue open, as I still have to speedup the test suite, so we can run it on travis without timing out.

**Comment by remysucre** [comment] 2018-09-20 02:18
That makes sense, nice! There might be some caching I can do on travis that may speed up installation etc. And the Travis time limit is 50 min for each job where some thing should be printed every 10 min. But it's probably still a good idea to speed up the tests.

**Comment by ryzhyk** [comment] 2018-09-21 09:11
As of #102 the complete test suite runs in Travis

**Closed by ryzhyk** 2018-09-21 09:11 UTC
Labels: enhancement
